
/**
 * 그룹별 조건에 맞는 식당 목록 출력하기
 *  2. 'MEMBER_PROFILE와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하는 SQL문을 작성해주세요.
 *      회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력되도록 작성해주시고, 결과는 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순 정렬해주세요.
 */
public class Programmers_SQL_Join_Q2 {

/*
    SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW .REVIEW_TEXT, DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d')
    FROM MEMBER_PROFILE
    INNER JOIN REST_REVIEW ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
    WHERE MEMBER_PROFILE.MEMBER_NAME = (SELECT MEMBER_PROFILE.MEMBER_NAME
    FROM MEMBER_PROFILE
    INNER JOIN REST_REVIEW ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
    GROUP BY MEMBER_PROFILE.MEMBER_NAME
    ORDER BY COUNT(MEMBER_PROFILE.MEMBER_NAME) DESC LIMIT 1)
    ORDER BY REST_REVIEW.REVIEW_DATE, REST_REVIEW.REVIEW_TEXT ASC
    */

}
